### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'plots_relations/best_selection_GOOG_neg.json'

### ISSUE THREAD

**Issue by AmahleandElihle** [Leci37/stocks-prediction-Machine-learning-RealTime-telegram#6]
@Leci37 good work, I'm trying to deploy model by running the file Model_creation_models_for_a_stock.py, it's looking for json which are not populated. 

Please assist on how one can generate them.

We also be contributing this work once we get the pipeline working. It was a bit hard to get to Model_creation_models_for_a_stock.py but we did.
Many thanks,
A&E

**Comment by Leci37** [comment]
the ticket makes me very happy 

Once you have reached `Model_creation_models_for_a_stock.py,` it is because you have executed steps 1 and 2 before.

What error do you get? You can write me at _**leciluis@gmial.com**_ , so I can help you via telegram. 

`plots_relations/best_selection_GOOG_neg.json`, this is because you have not executed step 2 
in `Model_creation_scoring.py` 
```python
list_stocks = a_manage_stocks_dict.DICT_COMPANYS[CSV_NAME]
list_stocks have to contain "GOOG" ticket 
```

_**more details**_ https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram#2-filtering-technical-indicators with "GOOG" in the configuration

**Comment by charleshm** [comment]
i got the same problem, need new a folder name "plots_relations" before run the pipeline

**Comment by charleshm** [comment]
i got the same problem, when i excute Model_creation_scoring.py,  i didn't find where plots_relations/best_selection_GOOG_neg.json generated? can u give some suggestion

**Comment by charleshm** [comment]
Feature_selection_json_columns.py has been deleted in newest version,  Model_creation_models_for_a_stock.py cannot run success

**Comment by charleshm** [comment]
new pipeline need to fix some code, now it run success, thanks for your excellent job, i will learn more details these day.

**Comment by Leci37** [comment]
Good morning ,

I have just updated the documentation and the erroneous paths , you can see it at
https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/tree/master#quick-start-up-run-your-own-models
I'm closing the ticket.

P.S.: I always welcome a second opinion on https://github.com/Leci37/stocks-prediction-Machine-learning-RealTime-telegram/tree/master#possible-improvements
